apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketplace-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marketplace-service
  template:
    metadata:
      labels:
        app: marketplace-service
    spec:
      containers:
        - name: marketplace-service
          image: ghcr.io/${GITHUB_REPOSITORY}:marketplace-service-${GITHUB_SHA}
          ports:
            - containerPort: 4006
          livenessProbe:
            httpGet:
              path: /health
              port: 4006
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 4006
            initialDelaySeconds: 5
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: marketplace-service
spec:
  selector:
    app: marketplace-service
  ports:
    - protocol: TCP
      port: 4006
      targetPort: 4006
  type: ClusterIP
